var annotated_dup =
[
    [ "GOAT", "namespace_g_o_a_t.html", [
      [ "maths", "namespace_g_o_a_t_1_1maths.html", [
        [ "Matrix", "class_g_o_a_t_1_1maths_1_1_matrix.html", "class_g_o_a_t_1_1maths_1_1_matrix" ],
        [ "Vector", "class_g_o_a_t_1_1maths_1_1_vector.html", "class_g_o_a_t_1_1maths_1_1_vector" ]
      ] ],
      [ "raytracing", "namespace_g_o_a_t_1_1raytracing.html", [
        [ "Box", "class_g_o_a_t_1_1raytracing_1_1_box.html", "class_g_o_a_t_1_1raytracing_1_1_box" ],
        [ "Cone", "class_g_o_a_t_1_1raytracing_1_1_cone.html", "class_g_o_a_t_1_1raytracing_1_1_cone" ],
        [ "Detector", "class_g_o_a_t_1_1raytracing_1_1_detector.html", "class_g_o_a_t_1_1raytracing_1_1_detector" ],
        [ "DetectorPlane", "class_g_o_a_t_1_1raytracing_1_1_detector_plane.html", "class_g_o_a_t_1_1raytracing_1_1_detector_plane" ],
        [ "Ellipsoid", "class_g_o_a_t_1_1raytracing_1_1_ellipsoid.html", "class_g_o_a_t_1_1raytracing_1_1_ellipsoid" ],
        [ "Gauss", "struct_g_o_a_t_1_1raytracing_1_1_gauss.html", "struct_g_o_a_t_1_1raytracing_1_1_gauss" ],
        [ "GlobalParms", "class_g_o_a_t_1_1raytracing_1_1_global_parms.html", "class_g_o_a_t_1_1raytracing_1_1_global_parms" ],
        [ "grid", "class_g_o_a_t_1_1raytracing_1_1grid.html", "class_g_o_a_t_1_1raytracing_1_1grid" ],
        [ "gridEntry", "struct_g_o_a_t_1_1raytracing_1_1grid_entry.html", "struct_g_o_a_t_1_1raytracing_1_1grid_entry" ],
        [ "indexList", "struct_g_o_a_t_1_1raytracing_1_1index_list.html", "struct_g_o_a_t_1_1raytracing_1_1index_list" ],
        [ "IRay", "class_g_o_a_t_1_1raytracing_1_1_i_ray.html", "class_g_o_a_t_1_1raytracing_1_1_i_ray" ],
        [ "LightSrc", "class_g_o_a_t_1_1raytracing_1_1_light_src.html", "class_g_o_a_t_1_1raytracing_1_1_light_src" ],
        [ "LightSrcGauss", "class_g_o_a_t_1_1raytracing_1_1_light_src_gauss.html", "class_g_o_a_t_1_1raytracing_1_1_light_src_gauss" ],
        [ "LightSrcGauss_mc", "class_g_o_a_t_1_1raytracing_1_1_light_src_gauss__mc.html", "class_g_o_a_t_1_1raytracing_1_1_light_src_gauss__mc" ],
        [ "LightSrcPlane", "class_g_o_a_t_1_1raytracing_1_1_light_src_plane.html", "class_g_o_a_t_1_1raytracing_1_1_light_src_plane" ],
        [ "LightSrcPlane_mc", "class_g_o_a_t_1_1raytracing_1_1_light_src_plane__mc.html", "class_g_o_a_t_1_1raytracing_1_1_light_src_plane__mc" ],
        [ "MemInfo", "struct_g_o_a_t_1_1raytracing_1_1_mem_info.html", "struct_g_o_a_t_1_1raytracing_1_1_mem_info" ],
        [ "objectInfo", "struct_g_o_a_t_1_1raytracing_1_1object_info.html", "struct_g_o_a_t_1_1raytracing_1_1object_info" ],
        [ "ObjectShape", "class_g_o_a_t_1_1raytracing_1_1_object_shape.html", "class_g_o_a_t_1_1raytracing_1_1_object_shape" ],
        [ "Octree", "class_g_o_a_t_1_1raytracing_1_1_octree.html", "class_g_o_a_t_1_1raytracing_1_1_octree" ],
        [ "OptProp", "struct_g_o_a_t_1_1raytracing_1_1_opt_prop.html", "struct_g_o_a_t_1_1raytracing_1_1_opt_prop" ],
        [ "Plane", "class_g_o_a_t_1_1raytracing_1_1_plane.html", "class_g_o_a_t_1_1raytracing_1_1_plane" ],
        [ "Point", "struct_g_o_a_t_1_1raytracing_1_1_point.html", "struct_g_o_a_t_1_1raytracing_1_1_point" ],
        [ "pulseCalculation", "class_g_o_a_t_1_1raytracing_1_1pulse_calculation.html", "class_g_o_a_t_1_1raytracing_1_1pulse_calculation" ],
        [ "Ray_pow", "class_g_o_a_t_1_1raytracing_1_1_ray__pow.html", "class_g_o_a_t_1_1raytracing_1_1_ray__pow" ],
        [ "RayBase", "class_g_o_a_t_1_1raytracing_1_1_ray_base.html", "class_g_o_a_t_1_1raytracing_1_1_ray_base" ],
        [ "rayListEntry", "struct_g_o_a_t_1_1raytracing_1_1ray_list_entry.html", "struct_g_o_a_t_1_1raytracing_1_1ray_list_entry" ],
        [ "Raytrace", "class_g_o_a_t_1_1raytracing_1_1_raytrace.html", "class_g_o_a_t_1_1raytracing_1_1_raytrace" ],
        [ "Raytrace_Inel", "class_g_o_a_t_1_1raytracing_1_1_raytrace___inel.html", "class_g_o_a_t_1_1raytracing_1_1_raytrace___inel" ],
        [ "Raytrace_OT", "class_g_o_a_t_1_1raytracing_1_1_raytrace___o_t.html", "class_g_o_a_t_1_1raytracing_1_1_raytrace___o_t" ],
        [ "Raytrace_Path", "class_g_o_a_t_1_1raytracing_1_1_raytrace___path.html", "class_g_o_a_t_1_1raytracing_1_1_raytrace___path" ],
        [ "Raytrace_pure", "class_g_o_a_t_1_1raytracing_1_1_raytrace__pure.html", "class_g_o_a_t_1_1raytracing_1_1_raytrace__pure" ],
        [ "Raytrace_usp", "class_g_o_a_t_1_1raytracing_1_1_raytrace__usp.html", "class_g_o_a_t_1_1raytracing_1_1_raytrace__usp" ],
        [ "RRTParms", "struct_g_o_a_t_1_1raytracing_1_1_r_r_t_parms.html", "struct_g_o_a_t_1_1raytracing_1_1_r_r_t_parms" ],
        [ "RRTParmsInfo", "class_g_o_a_t_1_1raytracing_1_1_r_r_t_parms_info.html", "class_g_o_a_t_1_1raytracing_1_1_r_r_t_parms_info" ],
        [ "Scene", "class_g_o_a_t_1_1raytracing_1_1_scene.html", "class_g_o_a_t_1_1raytracing_1_1_scene" ],
        [ "shortPulse", "class_g_o_a_t_1_1raytracing_1_1short_pulse.html", "class_g_o_a_t_1_1raytracing_1_1short_pulse" ],
        [ "stepEntry", "struct_g_o_a_t_1_1raytracing_1_1step_entry.html", "struct_g_o_a_t_1_1raytracing_1_1step_entry" ],
        [ "StrahlArray", "struct_g_o_a_t_1_1raytracing_1_1_strahl_array.html", "struct_g_o_a_t_1_1raytracing_1_1_strahl_array" ],
        [ "StrahlInfo", "struct_g_o_a_t_1_1raytracing_1_1_strahl_info.html", "struct_g_o_a_t_1_1raytracing_1_1_strahl_info" ],
        [ "SuperArray", "class_g_o_a_t_1_1raytracing_1_1_super_array.html", "class_g_o_a_t_1_1raytracing_1_1_super_array" ],
        [ "SuperGrid", "class_g_o_a_t_1_1raytracing_1_1_super_grid.html", "class_g_o_a_t_1_1raytracing_1_1_super_grid" ],
        [ "surface", "class_g_o_a_t_1_1raytracing_1_1surface.html", "class_g_o_a_t_1_1raytracing_1_1surface" ],
        [ "SysMemInfo", "struct_g_o_a_t_1_1raytracing_1_1_sys_mem_info.html", "struct_g_o_a_t_1_1raytracing_1_1_sys_mem_info" ],
        [ "Trafo", "class_g_o_a_t_1_1raytracing_1_1_trafo.html", "class_g_o_a_t_1_1raytracing_1_1_trafo" ],
        [ "TrafoParms", "struct_g_o_a_t_1_1raytracing_1_1_trafo_parms.html", "struct_g_o_a_t_1_1raytracing_1_1_trafo_parms" ],
        [ "triangle", "class_g_o_a_t_1_1raytracing_1_1triangle.html", "class_g_o_a_t_1_1raytracing_1_1triangle" ],
        [ "tubedRay", "class_g_o_a_t_1_1raytracing_1_1tubed_ray.html", "class_g_o_a_t_1_1raytracing_1_1tubed_ray" ],
        [ "tubedRayBuffer", "struct_g_o_a_t_1_1raytracing_1_1tubed_ray_buffer.html", "struct_g_o_a_t_1_1raytracing_1_1tubed_ray_buffer" ],
        [ "wavelengthRange", "struct_g_o_a_t_1_1raytracing_1_1wavelength_range.html", "struct_g_o_a_t_1_1raytracing_1_1wavelength_range" ]
      ] ],
      [ "XML", "namespace_g_o_a_t_1_1_x_m_l.html", [
        [ "xmlReader", "class_g_o_a_t_1_1_x_m_l_1_1xml_reader.html", "class_g_o_a_t_1_1_x_m_l_1_1xml_reader" ]
      ] ]
    ] ],
    [ "tinyxml2", "namespacetinyxml2.html", [
      [ "DynArray", "classtinyxml2_1_1_dyn_array.html", "classtinyxml2_1_1_dyn_array" ],
      [ "MemPool", "classtinyxml2_1_1_mem_pool.html", "classtinyxml2_1_1_mem_pool" ],
      [ "MemPoolT", "classtinyxml2_1_1_mem_pool_t.html", "classtinyxml2_1_1_mem_pool_t" ],
      [ "StrPair", "classtinyxml2_1_1_str_pair.html", "classtinyxml2_1_1_str_pair" ],
      [ "XMLAttribute", "classtinyxml2_1_1_x_m_l_attribute.html", "classtinyxml2_1_1_x_m_l_attribute" ],
      [ "XMLComment", "classtinyxml2_1_1_x_m_l_comment.html", "classtinyxml2_1_1_x_m_l_comment" ],
      [ "XMLConstHandle", "classtinyxml2_1_1_x_m_l_const_handle.html", "classtinyxml2_1_1_x_m_l_const_handle" ],
      [ "XMLDeclaration", "classtinyxml2_1_1_x_m_l_declaration.html", "classtinyxml2_1_1_x_m_l_declaration" ],
      [ "XMLDocument", "classtinyxml2_1_1_x_m_l_document.html", "classtinyxml2_1_1_x_m_l_document" ],
      [ "XMLElement", "classtinyxml2_1_1_x_m_l_element.html", "classtinyxml2_1_1_x_m_l_element" ],
      [ "XMLHandle", "classtinyxml2_1_1_x_m_l_handle.html", "classtinyxml2_1_1_x_m_l_handle" ],
      [ "XMLNode", "classtinyxml2_1_1_x_m_l_node.html", "classtinyxml2_1_1_x_m_l_node" ],
      [ "XMLPrinter", "classtinyxml2_1_1_x_m_l_printer.html", "classtinyxml2_1_1_x_m_l_printer" ],
      [ "XMLText", "classtinyxml2_1_1_x_m_l_text.html", "classtinyxml2_1_1_x_m_l_text" ],
      [ "XMLUnknown", "classtinyxml2_1_1_x_m_l_unknown.html", "classtinyxml2_1_1_x_m_l_unknown" ],
      [ "XMLUtil", "classtinyxml2_1_1_x_m_l_util.html", null ],
      [ "XMLVisitor", "classtinyxml2_1_1_x_m_l_visitor.html", "classtinyxml2_1_1_x_m_l_visitor" ]
    ] ]
];