var annotated_dup =
[
    [ "GOAT", "namespace_g_o_a_t.html", [
      [ "maths", "namespace_g_o_a_t_1_1maths.html", [
        [ "Matrix", "class_g_o_a_t_1_1maths_1_1_matrix.html", "class_g_o_a_t_1_1maths_1_1_matrix" ],
        [ "Vector", "class_g_o_a_t_1_1maths_1_1_vector.html", "class_g_o_a_t_1_1maths_1_1_vector" ]
      ] ],
      [ "raytracing", "namespace_g_o_a_t_1_1raytracing.html", [
        [ "asphericLensSide", "struct_g_o_a_t_1_1raytracing_1_1aspheric_lens_side.html", "struct_g_o_a_t_1_1raytracing_1_1aspheric_lens_side" ],
        [ "asphericLensParms", "struct_g_o_a_t_1_1raytracing_1_1aspheric_lens_parms.html", "struct_g_o_a_t_1_1raytracing_1_1aspheric_lens_parms" ],
        [ "asphericLens", "class_g_o_a_t_1_1raytracing_1_1aspheric_lens.html", "class_g_o_a_t_1_1raytracing_1_1aspheric_lens" ],
        [ "Box", "class_g_o_a_t_1_1raytracing_1_1_box.html", "class_g_o_a_t_1_1raytracing_1_1_box" ],
        [ "Cone", "class_g_o_a_t_1_1raytracing_1_1_cone.html", "class_g_o_a_t_1_1raytracing_1_1_cone" ],
        [ "Detector", "class_g_o_a_t_1_1raytracing_1_1_detector.html", "class_g_o_a_t_1_1raytracing_1_1_detector" ],
        [ "DetectorPlane", "class_g_o_a_t_1_1raytracing_1_1_detector_plane.html", "class_g_o_a_t_1_1raytracing_1_1_detector_plane" ],
        [ "Ellipsoid", "class_g_o_a_t_1_1raytracing_1_1_ellipsoid.html", "class_g_o_a_t_1_1raytracing_1_1_ellipsoid" ],
        [ "TrafoParms", "struct_g_o_a_t_1_1raytracing_1_1_trafo_parms.html", "struct_g_o_a_t_1_1raytracing_1_1_trafo_parms" ],
        [ "Trafo", "class_g_o_a_t_1_1raytracing_1_1_trafo.html", "class_g_o_a_t_1_1raytracing_1_1_trafo" ],
        [ "grid", "class_g_o_a_t_1_1raytracing_1_1grid.html", "class_g_o_a_t_1_1raytracing_1_1grid" ],
        [ "stepEntry", "struct_g_o_a_t_1_1raytracing_1_1step_entry.html", "struct_g_o_a_t_1_1raytracing_1_1step_entry" ],
        [ "gridEntry", "struct_g_o_a_t_1_1raytracing_1_1grid_entry.html", "struct_g_o_a_t_1_1raytracing_1_1grid_entry" ],
        [ "IRay", "class_g_o_a_t_1_1raytracing_1_1_i_ray.html", "class_g_o_a_t_1_1raytracing_1_1_i_ray" ],
        [ "lensSide", "struct_g_o_a_t_1_1raytracing_1_1lens_side.html", "struct_g_o_a_t_1_1raytracing_1_1lens_side" ],
        [ "lensParms", "struct_g_o_a_t_1_1raytracing_1_1lens_parms.html", "struct_g_o_a_t_1_1raytracing_1_1lens_parms" ],
        [ "LightSrc", "class_g_o_a_t_1_1raytracing_1_1_light_src.html", "class_g_o_a_t_1_1raytracing_1_1_light_src" ],
        [ "LightSrcPlane", "class_g_o_a_t_1_1raytracing_1_1_light_src_plane.html", "class_g_o_a_t_1_1raytracing_1_1_light_src_plane" ],
        [ "LightSrcRing", "class_g_o_a_t_1_1raytracing_1_1_light_src_ring.html", "class_g_o_a_t_1_1raytracing_1_1_light_src_ring" ],
        [ "LightSrcGauss", "class_g_o_a_t_1_1raytracing_1_1_light_src_gauss.html", "class_g_o_a_t_1_1raytracing_1_1_light_src_gauss" ],
        [ "LightSrcGauss_mc", "class_g_o_a_t_1_1raytracing_1_1_light_src_gauss__mc.html", "class_g_o_a_t_1_1raytracing_1_1_light_src_gauss__mc" ],
        [ "LightSrcPlane_mc", "class_g_o_a_t_1_1raytracing_1_1_light_src_plane__mc.html", "class_g_o_a_t_1_1raytracing_1_1_light_src_plane__mc" ],
        [ "LightSrcRing_mc", "class_g_o_a_t_1_1raytracing_1_1_light_src_ring__mc.html", "class_g_o_a_t_1_1raytracing_1_1_light_src_ring__mc" ],
        [ "LightSrcRingGauss_mc", "class_g_o_a_t_1_1raytracing_1_1_light_src_ring_gauss__mc.html", "class_g_o_a_t_1_1raytracing_1_1_light_src_ring_gauss__mc" ],
        [ "MemInfo", "struct_g_o_a_t_1_1raytracing_1_1_mem_info.html", "struct_g_o_a_t_1_1raytracing_1_1_mem_info" ],
        [ "SysMemInfo", "struct_g_o_a_t_1_1raytracing_1_1_sys_mem_info.html", "struct_g_o_a_t_1_1raytracing_1_1_sys_mem_info" ],
        [ "ObjectShape", "class_g_o_a_t_1_1raytracing_1_1_object_shape.html", "class_g_o_a_t_1_1raytracing_1_1_object_shape" ],
        [ "Octree", "class_g_o_a_t_1_1raytracing_1_1_octree.html", "class_g_o_a_t_1_1raytracing_1_1_octree" ],
        [ "Plane", "class_g_o_a_t_1_1raytracing_1_1_plane.html", "class_g_o_a_t_1_1raytracing_1_1_plane" ],
        [ "pulseCalculation", "class_g_o_a_t_1_1raytracing_1_1pulse_calculation.html", "class_g_o_a_t_1_1raytracing_1_1pulse_calculation" ],
        [ "pulseCalculation_field", "class_g_o_a_t_1_1raytracing_1_1pulse_calculation__field.html", "class_g_o_a_t_1_1raytracing_1_1pulse_calculation__field" ],
        [ "pulseCalculation_Field", "class_g_o_a_t_1_1raytracing_1_1pulse_calculation___field.html", "class_g_o_a_t_1_1raytracing_1_1pulse_calculation___field" ],
        [ "Ray_pow", "class_g_o_a_t_1_1raytracing_1_1_ray__pow.html", "class_g_o_a_t_1_1raytracing_1_1_ray__pow" ],
        [ "RayBase", "class_g_o_a_t_1_1raytracing_1_1_ray_base.html", "class_g_o_a_t_1_1raytracing_1_1_ray_base" ],
        [ "Scene", "class_g_o_a_t_1_1raytracing_1_1_scene.html", "class_g_o_a_t_1_1raytracing_1_1_scene" ],
        [ "Raytrace", "class_g_o_a_t_1_1raytracing_1_1_raytrace.html", "class_g_o_a_t_1_1raytracing_1_1_raytrace" ],
        [ "Raytrace_OT", "class_g_o_a_t_1_1raytracing_1_1_raytrace___o_t.html", "class_g_o_a_t_1_1raytracing_1_1_raytrace___o_t" ],
        [ "Raytrace_Path", "class_g_o_a_t_1_1raytracing_1_1_raytrace___path.html", "class_g_o_a_t_1_1raytracing_1_1_raytrace___path" ],
        [ "Raytrace_pure", "class_g_o_a_t_1_1raytracing_1_1_raytrace__pure.html", "class_g_o_a_t_1_1raytracing_1_1_raytrace__pure" ],
        [ "Raytrace_Field", "class_g_o_a_t_1_1raytracing_1_1_raytrace___field.html", "class_g_o_a_t_1_1raytracing_1_1_raytrace___field" ],
        [ "Raytrace_Field_usp", "class_g_o_a_t_1_1raytracing_1_1_raytrace___field__usp.html", "class_g_o_a_t_1_1raytracing_1_1_raytrace___field__usp" ],
        [ "RRTParms", "struct_g_o_a_t_1_1raytracing_1_1_r_r_t_parms.html", "struct_g_o_a_t_1_1raytracing_1_1_r_r_t_parms" ],
        [ "Raytrace_Inel", "class_g_o_a_t_1_1raytracing_1_1_raytrace___inel.html", "class_g_o_a_t_1_1raytracing_1_1_raytrace___inel" ],
        [ "Raytrace_usp", "class_g_o_a_t_1_1raytracing_1_1_raytrace__usp.html", "class_g_o_a_t_1_1raytracing_1_1_raytrace__usp" ],
        [ "Point", "struct_g_o_a_t_1_1raytracing_1_1_point.html", "struct_g_o_a_t_1_1raytracing_1_1_point" ],
        [ "OptProp", "struct_g_o_a_t_1_1raytracing_1_1_opt_prop.html", "struct_g_o_a_t_1_1raytracing_1_1_opt_prop" ],
        [ "StrahlInfo", "struct_g_o_a_t_1_1raytracing_1_1_strahl_info.html", "struct_g_o_a_t_1_1raytracing_1_1_strahl_info" ],
        [ "StrahlArray", "struct_g_o_a_t_1_1raytracing_1_1_strahl_array.html", "struct_g_o_a_t_1_1raytracing_1_1_strahl_array" ],
        [ "objectInfo", "struct_g_o_a_t_1_1raytracing_1_1object_info.html", "struct_g_o_a_t_1_1raytracing_1_1object_info" ],
        [ "RRTParmsInfo", "class_g_o_a_t_1_1raytracing_1_1_r_r_t_parms_info.html", "class_g_o_a_t_1_1raytracing_1_1_r_r_t_parms_info" ],
        [ "GlobalParms", "class_g_o_a_t_1_1raytracing_1_1_global_parms.html", "class_g_o_a_t_1_1raytracing_1_1_global_parms" ],
        [ "wavelengthRange", "struct_g_o_a_t_1_1raytracing_1_1wavelength_range.html", "struct_g_o_a_t_1_1raytracing_1_1wavelength_range" ],
        [ "rayListEntry", "struct_g_o_a_t_1_1raytracing_1_1ray_list_entry.html", "struct_g_o_a_t_1_1raytracing_1_1ray_list_entry" ],
        [ "indexList", "struct_g_o_a_t_1_1raytracing_1_1index_list.html", "struct_g_o_a_t_1_1raytracing_1_1index_list" ],
        [ "shortPulse", "class_g_o_a_t_1_1raytracing_1_1short_pulse.html", "class_g_o_a_t_1_1raytracing_1_1short_pulse" ],
        [ "sphericLens", "class_g_o_a_t_1_1raytracing_1_1spheric_lens.html", "class_g_o_a_t_1_1raytracing_1_1spheric_lens" ],
        [ "SuperArray", "class_g_o_a_t_1_1raytracing_1_1_super_array.html", "class_g_o_a_t_1_1raytracing_1_1_super_array" ],
        [ "SuperGrid", "class_g_o_a_t_1_1raytracing_1_1_super_grid.html", "class_g_o_a_t_1_1raytracing_1_1_super_grid" ],
        [ "surface", "class_g_o_a_t_1_1raytracing_1_1surface.html", "class_g_o_a_t_1_1raytracing_1_1surface" ],
        [ "triangle", "class_g_o_a_t_1_1raytracing_1_1triangle.html", "class_g_o_a_t_1_1raytracing_1_1triangle" ],
        [ "tubedRayBuffer", "struct_g_o_a_t_1_1raytracing_1_1tubed_ray_buffer.html", "struct_g_o_a_t_1_1raytracing_1_1tubed_ray_buffer" ],
        [ "Gauss", "struct_g_o_a_t_1_1raytracing_1_1_gauss.html", "struct_g_o_a_t_1_1raytracing_1_1_gauss" ],
        [ "tubedRay", "class_g_o_a_t_1_1raytracing_1_1tubed_ray.html", "class_g_o_a_t_1_1raytracing_1_1tubed_ray" ]
      ] ]
    ] ]
];